//! NeoBrowser — a fast, stealthy MCP browser-automation server that drives real
//! Chrome via CDP. `serve` runs the MCP server (default); `doctor` checks the
//! environment; `tools` prints the tool catalog for humans/AIs.

use neobrowser::{cdp, chrome, mcp, paths, tool_impls};

use std::time::Duration;

const HELP: &str = "\
neobrowser — MCP browser automation over real Chrome

USAGE:
  neobrowser [serve]     Run the MCP server on stdio (default)
  neobrowser doctor      Check Chrome discovery + a live CDP smoke test
  neobrowser tools       Print the tool catalog as JSON
  neobrowser tools --markdown   Print the tool catalog as Markdown
  neobrowser --version   Print the version

Key env vars: NEOBROWSER_REAL_PROFILE, NEOBROWSER_ATTACH_PORT,
NEOBROWSER_CHROME_BIN, NEOBROWSER_HOME, NEOBROWSER_PROXY, ANTHROPIC_API_KEY.";

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .with_writer(std::io::stderr)
        .init();

    let arg = std::env::args().nth(1).unwrap_or_default();
    match arg.as_str() {
        "doctor" => doctor().await,
        "tools" => print_tools(),
        "--version" | "-v" => println!("{}", env!("CARGO_PKG_VERSION")),
        "--help" | "-h" => println!("{HELP}"),
        "" | "serve" => mcp::serve().await,
        other => {
            eprintln!("neobrowser: unknown command '{other}'.\n\n{HELP}");
            std::process::exit(2);
        }
    }
}

/// Print the tool catalog. `tools --markdown` renders a docs-friendly table.
fn print_tools() {
    let registry = tool_impls::build_registry();
    let descriptors = registry.descriptors();
    let markdown = std::env::args().any(|a| a == "--markdown" || a == "md");
    if !markdown {
        println!(
            "{}",
            serde_json::to_string_pretty(&descriptors).unwrap_or_else(|_| "[]".into())
        );
        return;
    }
    println!("# NeoBrowser tools ({})\n", descriptors.len());
    println!("Generated by `neobrowser tools --markdown`.\n");
    for d in &descriptors {
        let name = d.get("name").and_then(|v| v.as_str()).unwrap_or("");
        let desc = d.get("description").and_then(|v| v.as_str()).unwrap_or("");
        println!("## `{name}`\n\n{desc}\n");
        let props = d
            .get("inputSchema")
            .and_then(|s| s.get("properties"))
            .and_then(|p| p.as_object());
        let required: Vec<&str> = d
            .get("inputSchema")
            .and_then(|s| s.get("required"))
            .and_then(|r| r.as_array())
            .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        match props {
            Some(p) if !p.is_empty() => {
                println!("| param | type | required | description |");
                println!("|---|---|---|---|");
                for (k, v) in p {
                    let ty = v.get("type").and_then(|t| t.as_str()).unwrap_or("");
                    let pd = v.get("description").and_then(|t| t.as_str()).unwrap_or("");
                    let req = if required.contains(&k.as_str()) {
                        "yes"
                    } else {
                        ""
                    };
                    println!("| `{k}` | {ty} | {req} | {pd} |");
                }
                println!();
            }
            _ => println!("_No parameters._\n"),
        }
    }
}

/// Report Chrome discovery, version, and home-dir layout — the Rust equivalent of
/// the Python `neobrowser doctor`.
async fn doctor() {
    let bin = chrome::chrome_bin();
    println!("NeoBrowser doctor");
    println!("  home:        {}", paths::home().display());
    println!("  chrome bin:  {}", bin.display());
    println!("  chrome found: {}", bin.exists());
    match chrome::detect_chrome_major(bin) {
        Some(major) => println!("  chrome major: {major}"),
        None => println!("  chrome major: <unknown>"),
    }
    match chrome::chrome_user_agent() {
        Some(ua) => println!("  user-agent:  {ua}"),
        None => println!("  user-agent:  <default>"),
    }
    // Prove the process/CDP path works end-to-end if Chrome is present.
    if bin.exists() {
        print!("  launch+CDP:  ");
        match smoke_test().await {
            Ok(title) => println!("ok (about:blank title={title:?})"),
            Err(e) => println!("FAILED: {e}"),
        }
    }
}

/// Launch headless Chrome, open a tab, connect CDP, evaluate a trivial expression.
async fn smoke_test() -> Result<String, String> {
    let profile = paths::profiles_base().join("doctor");
    let mut proc = chrome::ChromeProcess::launch(&profile)
        .await
        .map_err(|e| e.to_string())?;
    let result = async {
        chrome::wait_for_chrome(proc.port, Duration::from_secs(10))
            .await
            .map_err(|e| e.to_string())?;
        let tab = chrome::open_new_tab(proc.port)
            .await
            .map_err(|e| e.to_string())?;
        let client = cdp::CdpClient::connect(&tab.web_socket_debugger_url)
            .await
            .map_err(|e| e.to_string())?;
        client
            .send("Page.enable", serde_json::json!({}))
            .await
            .map_err(|e| e.to_string())?;
        let title = client
            .eval("document.title")
            .await
            .map_err(|e| e.to_string())?;
        Ok::<String, String>(title.as_str().unwrap_or("").to_string())
    }
    .await;
    proc.kill(true).await;
    result
}
