//! Script extraction and meta-refresh detection for HTML pages.

/// Script extracted from HTML for execution or pre-loading.
pub(crate) enum ScriptInfo {
    /// Inline `<script>` tag with JS source.
    Inline { content: String, is_module: bool },
    /// External `<script src="...">` tag.
    External { url: String, is_module: bool },
    /// `<link rel="modulepreload">` — fetch but don't execute as top-level.
    Preload { url: String },
}

impl ScriptInfo {
    /// URL for external scripts and preloads; None for inline.
    pub(crate) fn url(&self) -> Option<&str> {
        match self {
            Self::External { url, .. } | Self::Preload { url } => Some(url),
            Self::Inline { .. } => None,
        }
    }

    /// Whether this is an ES module (inline module or external module).
    pub(crate) fn is_module(&self) -> bool {
        match self {
            Self::Inline { is_module, .. } | Self::External { is_module, .. } => *is_module,
            Self::Preload { .. } => true,
        }
    }
}

/// URL patterns for scripts that are non-essential for content extraction.
///
/// These scripts handle UI interactivity, analytics, A/B testing, etc.
/// Skipping them saves both fetch time and V8 execution time.
const SKIP_SCRIPT_PATTERNS: &[&str] = &[
    // --- Frameworks / heavy bundles ---
    "react-dom",
    "react.production",
    "react-lib",
    "react-core",
    "scheduler.production",
    "chunk-vendors",
    "webpack-runtime",
    "polyfill",
    "regenerator-runtime",
    // --- GitHub-specific (100+ chunked modules, not needed for content) ---
    "app/assets/modules/github/",
    "github-elements",
    "primer-",
    "behaviors-",
    "notifications-global",
    "codespaces-",
    "repositories-",
    "code-menu-",
    "octicons-react",
    "element-registry",
    // --- Numbered chunk bundles (SPA code-splitting, not content) ---
    // Patterns like /12345-abcdef1234.js — numeric chunk IDs
    // These are handled by is_numeric_chunk() below
    // --- UI / interactivity (not needed for content) ---
    "service-worker",
    "sw.js",
    "workbox",
    "push-notifications",
    "web-vitals",
    "performance-mark",
    "intersection-observer",
    "resize-observer",
    "mutation-observer",
    // --- Cookie consent / GDPR ---
    "cookie-consent",
    "cookieconsent",
    "gdpr",
    "onetrust",
    "trustarc",
    // --- Social widgets ---
    "platform.twitter",
    "connect.facebook",
    "platform.linkedin",
    "widgets.js",
    // --- Chat / support widgets ---
    "zendesk",
    "intercom",
    "drift",
    "crisp",
    "tawk",
    "livechat",
    // --- A/B testing ---
    "optimizely",
    "vwo",
    "abtasty",
    // --- Feature flags ---
    "launchdarkly",
    "statsig",
    "featureflag",
    // --- Ad / monetization ---
    "adsense",
    "googletag",
    "prebid",
    "amazon-adsystem",
    "outbrain",
    "taboola",
    // --- NYTimes / news-specific ---
    "nyt-a",
    "nyt-analytics",
    "nyt-gdpr",
    "nyt-ads",
    "vi-assets",
    // --- YouTube-specific ---
    "www-player",
    "www-tampering",
    "desktop_polymer",
    "scheduler",
];

/// Check if a filename looks like a numeric code-split chunk: /12345-abcdef.js
///
/// These are generated by bundlers (Webpack, Turbopack, Vite) and contain
/// UI component code, not page content.
fn is_numeric_chunk(url: &str) -> bool {
    // Extract the filename from the URL, stripping query string.
    let path_part = url.split('?').next().unwrap_or(url);
    let filename = match path_part.rsplit('/').next() {
        Some(f) => f,
        None => return false,
    };
    // Must end in .js and start with digits followed by a dash or dot.
    if !filename.ends_with(".js") {
        return false;
    }
    let name = &filename[..filename.len() - 3]; // strip .js
    // Pattern 1: digits-hexhash.js (e.g. "99328-91354dc331fd4cdd.js")
    // Pattern 2: digits.lang.js (e.g. "3612.en.js") — SO/webpack locale chunks
    if let Some(dash_pos) = name.find('-') {
        let prefix = &name[..dash_pos];
        let suffix = &name[dash_pos + 1..];
        if prefix.len() >= 2
            && prefix.chars().all(|c| c.is_ascii_digit())
            && suffix.len() >= 8
            && suffix.chars().all(|c| c.is_ascii_hexdigit())
        {
            return true;
        }
    }
    // digits.xx.js or digits.xxx.js (locale chunks like 3612.en.js)
    if let Some(dot_pos) = name.find('.') {
        let prefix = &name[..dot_pos];
        if prefix.len() >= 2 && prefix.chars().all(|c| c.is_ascii_digit()) {
            return true;
        }
    }
    false
}

/// Check if a script URL matches a non-essential pattern and should be skipped.
pub(crate) fn is_skippable_script(url: &str) -> bool {
    let lower = url.to_lowercase();
    // Always skip telemetry URLs.
    if neo_http::classify::is_telemetry_url(&lower) {
        return true;
    }
    // Skip named patterns.
    if SKIP_SCRIPT_PATTERNS.iter().any(|p| lower.contains(p)) {
        return true;
    }
    // Skip numeric code-split chunks (e.g. /12345-abcdef1234.js).
    is_numeric_chunk(&lower)
}

/// Extract `<script>` tags and `<link rel="modulepreload">` from HTML.
///
/// Returns inline content, external URLs, and modulepreload URLs in document order.
/// Skips non-JS types (JSON, importmap, template, etc.).
/// Also filters out non-essential external scripts (analytics, frameworks, widgets).
pub(crate) fn extract_scripts(html: &str, base_url: &str) -> Vec<ScriptInfo> {
    use html5ever::parse_document;
    use html5ever::tendril::TendrilSink;
    use markup5ever_rcdom::RcDom;

    let dom = parse_document(RcDom::default(), Default::default()).one(html);

    let mut scripts = Vec::new();
    collect_all(&dom.document, base_url, &mut scripts);

    // Filter out non-essential scripts.
    let before = scripts.len();
    scripts.retain(|s| match s {
        ScriptInfo::External { url, .. } | ScriptInfo::Preload { url } => {
            !is_skippable_script(url)
        }
        // Skip large inline scripts (>20KB) -- these are typically
        // serialized state, analytics, or framework bootstrapping code.
        // Content-setting inline scripts are almost always small (<5KB).
        ScriptInfo::Inline { content, .. } => content.len() < 20_000,
    });
    let skipped = before - scripts.len();
    if skipped > 0 {
        eprintln!("[profile] scripts_filtered: {skipped} non-essential skipped");
    }

    scripts
}

/// Recursively walk the DOM collecting scripts and modulepreload links.
fn collect_all(node: &markup5ever_rcdom::Handle, base: &str, scripts: &mut Vec<ScriptInfo>) {
    use markup5ever_rcdom::NodeData;

    if let NodeData::Element {
        ref name,
        ref attrs,
        ..
    } = node.data
    {
        let local = name.local.as_ref();

        if local == "script" {
            collect_script(node, attrs, base, scripts);
        } else if local == "link" {
            collect_modulepreload(attrs, base, scripts);
        }
    }
    for child in node.children.borrow().iter() {
        collect_all(child, base, scripts);
    }
}

/// Extract a `<script>` element.
fn collect_script(
    node: &markup5ever_rcdom::Handle,
    attrs: &std::cell::RefCell<Vec<html5ever::Attribute>>,
    base: &str,
    scripts: &mut Vec<ScriptInfo>,
) {
    use markup5ever_rcdom::NodeData;

    let attrs_ref = attrs.borrow();
    let script_type = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "type")
        .map(|a| a.value.to_string())
        .unwrap_or_default();

    // Skip non-JS script types.
    let st = script_type.to_lowercase();
    if st.contains("json")
        || st.contains("importmap")
        || st.contains("template")
        || st.contains("html")
        || st.contains("x-")
    {
        return;
    }

    let is_module = script_type == "module";
    let src = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "src")
        .map(|a| a.value.to_string());

    if let Some(src) = src {
        let full = resolve_script_url(&src, base);
        scripts.push(ScriptInfo::External {
            url: full,
            is_module,
        });
    } else {
        drop(attrs_ref);
        let text: String = node
            .children
            .borrow()
            .iter()
            .filter_map(|c| match &c.data {
                NodeData::Text { contents } => Some(contents.borrow().to_string()),
                _ => None,
            })
            .collect();
        if !text.trim().is_empty() {
            scripts.push(ScriptInfo::Inline {
                content: text,
                is_module,
            });
        }
    }
}

/// Extract `<link rel="modulepreload" href="...">`.
fn collect_modulepreload(
    attrs: &std::cell::RefCell<Vec<html5ever::Attribute>>,
    base: &str,
    scripts: &mut Vec<ScriptInfo>,
) {
    let attrs_ref = attrs.borrow();
    let rel = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "rel")
        .map(|a| a.value.to_string())
        .unwrap_or_default();

    if rel != "modulepreload" {
        return;
    }

    if let Some(href) = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "href")
        .map(|a| a.value.to_string())
    {
        let full = resolve_script_url(&href, base);
        scripts.push(ScriptInfo::Preload { url: full });
    }
}

/// Detect `<meta http-equiv="refresh" content="...;url=...">` in HTML.
pub(crate) fn detect_meta_refresh(html: &str, base_url: &str) -> Option<String> {
    let lower = html.to_lowercase();
    let needle = "http-equiv";
    let mut search_from = 0;
    while let Some(pos) = lower[search_from..].find(needle) {
        let abs_pos = search_from + pos;
        search_from = abs_pos + needle.len();
        let surrounding = &lower[abs_pos..std::cmp::min(abs_pos + 100, lower.len())];
        if !surrounding.contains("refresh") {
            continue;
        }
        let tag_start = lower[..abs_pos].rfind('<').unwrap_or(abs_pos);
        let tag_end = lower[tag_start..]
            .find('>')
            .map(|p| tag_start + p)
            .unwrap_or(lower.len());
        let tag = &html[tag_start..tag_end];
        let tag_lower = tag.to_lowercase();
        if let Some(ci) = tag_lower.find("content=") {
            let after = &tag[ci + 8..];
            let (delim, start_offset) = if after.starts_with('"') {
                ('"', 1)
            } else if after.starts_with('\'') {
                ('\'', 1)
            } else {
                continue;
            };
            let content_str = &after[start_offset..];
            if let Some(end) = content_str.find(delim) {
                let content_val = &content_str[..end];
                let content_lower = content_val.to_lowercase();
                if let Some(url_pos) = content_lower.find("url=") {
                    let target = content_val[url_pos + 4..].trim();
                    if !target.is_empty() {
                        return Some(resolve_script_url(target, base_url));
                    }
                }
            }
        }
    }
    None
}

/// Resolve a script src URL against a base URL.
pub(crate) fn resolve_script_url(src: &str, base: &str) -> String {
    if src.starts_with("http") {
        src.to_string()
    } else if src.starts_with("//") {
        format!("https:{src}")
    } else if let Ok(base_url) = url::Url::parse(base) {
        base_url
            .join(src)
            .map(|u| u.to_string())
            .unwrap_or_else(|_| src.to_string())
    } else {
        src.to_string()
    }
}
