//! Script extraction, import map parsing, framework detection, and meta-refresh for HTML pages.

use neo_runtime::modules::ImportMap;

/// How a script should be scheduled for execution.
///
/// Approximates browser semantics: blocking scripts first, then deferred/module
/// scripts in document order, then async scripts in fetch-completion order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ScriptKind {
    /// `<script>...</script>` (no defer/async/type=module)
    InlineBlocking,
    /// `<script src="..."></script>` (no defer/async)
    ExternalBlocking,
    /// `<script defer src="...">`
    Defer,
    /// `<script async src="...">`
    Async,
    /// `<script type="module" src="...">` (implicitly defer)
    Module,
    /// `<script type="module" async src="...">`
    AsyncModule,
    /// `<script type="module">...</script>` (implicitly defer)
    InlineModule,
    /// `<script type="importmap">` — parsed separately, NOT executed as JS.
    ImportMap,
    /// Non-JS types: application/json, text/template, etc.
    Ignored,
}

/// Script extracted from HTML for execution or pre-loading.
pub(crate) enum ScriptInfo {
    /// Inline `<script>` tag with JS source.
    Inline {
        content: String,
        is_module: bool,
        kind: ScriptKind,
    },
    /// External `<script src="...">` tag.
    External {
        url: String,
        is_module: bool,
        kind: ScriptKind,
    },
    /// `<link rel="modulepreload">` — fetch but don't execute as top-level.
    Preload { url: String },
}

impl ScriptInfo {
    /// URL for external scripts and preloads; None for inline.
    pub(crate) fn url(&self) -> Option<&str> {
        match self {
            Self::External { url, .. } | Self::Preload { url } => Some(url),
            Self::Inline { .. } => None,
        }
    }

    /// Whether this is an ES module (inline module or external module).
    pub(crate) fn is_module(&self) -> bool {
        match self {
            Self::Inline { is_module, .. } | Self::External { is_module, .. } => *is_module,
            Self::Preload { .. } => true,
        }
    }

    /// The execution scheduling kind for this script.
    pub(crate) fn kind(&self) -> ScriptKind {
        match self {
            Self::Inline { kind, .. } | Self::External { kind, .. } => *kind,
            Self::Preload { .. } => ScriptKind::Module, // preloads behave as deferred modules
        }
    }
}

/// URL patterns for scripts that are non-essential for content extraction.
///
/// These scripts handle UI interactivity, analytics, A/B testing, etc.
/// Skipping them saves both fetch time and V8 execution time.
const SKIP_SCRIPT_PATTERNS: &[&str] = &[
    // --- Frameworks / heavy bundles ---
    "react-dom",
    "react.production",
    "react-lib",
    "react-core",
    "scheduler.production",
    "chunk-vendors",
    "webpack-runtime",
    "polyfill",
    "regenerator-runtime",
    // --- GitHub-specific (100+ chunked modules, not needed for content) ---
    "app/assets/modules/github/",
    "github-elements",
    "primer-",
    "behaviors-",
    "notifications-global",
    "codespaces-",
    "repositories-",
    "code-menu-",
    "octicons-react",
    "element-registry",
    // --- Numbered chunk bundles (SPA code-splitting, not content) ---
    // Patterns like /12345-abcdef1234.js — numeric chunk IDs
    // These are handled by is_numeric_chunk() below
    // --- UI / interactivity (not needed for content) ---
    "service-worker",
    "sw.js",
    "workbox",
    "push-notifications",
    "web-vitals",
    "performance-mark",
    "intersection-observer",
    "resize-observer",
    "mutation-observer",
    // --- Cookie consent / GDPR ---
    "cookie-consent",
    "cookieconsent",
    "gdpr",
    "onetrust",
    "trustarc",
    // --- Social widgets ---
    "platform.twitter",
    "connect.facebook",
    "platform.linkedin",
    "widgets.js",
    // --- Chat / support widgets ---
    "zendesk",
    "intercom",
    "drift",
    "crisp",
    "tawk",
    "livechat",
    // --- A/B testing ---
    "optimizely",
    "vwo",
    "abtasty",
    // --- Feature flags ---
    "launchdarkly",
    "statsig",
    "featureflag",
    // --- Ad / monetization ---
    "adsense",
    "googletag",
    "prebid",
    "amazon-adsystem",
    "outbrain",
    "taboola",
    // --- NYTimes / news-specific ---
    "nyt-a",
    "nyt-analytics",
    "nyt-gdpr",
    "nyt-ads",
    "vi-assets",
    // --- YouTube-specific ---
    "www-player",
    "www-tampering",
    "desktop_polymer",
    "scheduler",
];

/// Check if a filename looks like a numeric code-split chunk: /12345-abcdef.js
///
/// These are generated by bundlers (Webpack, Turbopack, Vite) and contain
/// UI component code, not page content.
fn is_numeric_chunk(url: &str) -> bool {
    // Extract the filename from the URL, stripping query string.
    let path_part = url.split('?').next().unwrap_or(url);
    let filename = match path_part.rsplit('/').next() {
        Some(f) => f,
        None => return false,
    };
    // Must end in .js and start with digits followed by a dash or dot.
    if !filename.ends_with(".js") {
        return false;
    }
    let name = &filename[..filename.len() - 3]; // strip .js
    // Pattern 1: digits-hexhash.js (e.g. "99328-91354dc331fd4cdd.js")
    // Pattern 2: digits.lang.js (e.g. "3612.en.js") — SO/webpack locale chunks
    if let Some(dash_pos) = name.find('-') {
        let prefix = &name[..dash_pos];
        let suffix = &name[dash_pos + 1..];
        if prefix.len() >= 2
            && prefix.chars().all(|c| c.is_ascii_digit())
            && suffix.len() >= 8
            && suffix.chars().all(|c| c.is_ascii_hexdigit())
        {
            return true;
        }
    }
    // digits.xx.js or digits.xxx.js (locale chunks like 3612.en.js)
    if let Some(dot_pos) = name.find('.') {
        let prefix = &name[..dot_pos];
        if prefix.len() >= 2 && prefix.chars().all(|c| c.is_ascii_digit()) {
            return true;
        }
    }
    false
}

/// Check if a script URL matches a non-essential pattern and should be skipped.
pub(crate) fn is_skippable_script(url: &str) -> bool {
    let lower = url.to_lowercase();
    // Always skip telemetry URLs.
    if neo_http::classify::is_telemetry_url(&lower) {
        return true;
    }
    // Skip named patterns.
    if SKIP_SCRIPT_PATTERNS.iter().any(|p| lower.contains(p)) {
        return true;
    }
    // Skip numeric code-split chunks (e.g. /12345-abcdef1234.js).
    is_numeric_chunk(&lower)
}

/// Extract `<script>` tags and `<link rel="modulepreload">` from HTML.
///
/// Returns inline content, external URLs, and modulepreload URLs in document order.
/// Each script is classified with a [`ScriptKind`] for execution ordering.
/// Skips non-JS types (JSON, template, etc.) but keeps importmaps for parsing.
/// Also filters out non-essential external scripts (analytics, frameworks, widgets).
pub(crate) fn extract_scripts(html: &str, base_url: &str) -> Vec<ScriptInfo> {
    use html5ever::parse_document;
    use html5ever::tendril::TendrilSink;
    use markup5ever_rcdom::RcDom;

    let dom = parse_document(RcDom::default(), Default::default()).one(html);

    let mut scripts = Vec::new();
    collect_all(&dom.document, base_url, &mut scripts);

    // Filter out non-essential scripts.
    let before = scripts.len();
    scripts.retain(|s| match s {
        ScriptInfo::External { url, .. } | ScriptInfo::Preload { url } => {
            !is_skippable_script(url)
        }
        // Skip large inline scripts (>20KB) -- these are typically
        // serialized state, analytics, or framework bootstrapping code.
        // Content-setting inline scripts are almost always small (<5KB).
        ScriptInfo::Inline { content, .. } => content.len() < 20_000,
    });
    let skipped = before - scripts.len();
    if skipped > 0 {
        eprintln!("[profile] scripts_filtered: {skipped} non-essential skipped");
    }

    scripts
}

/// Recursively walk the DOM collecting scripts and modulepreload links.
fn collect_all(node: &markup5ever_rcdom::Handle, base: &str, scripts: &mut Vec<ScriptInfo>) {
    use markup5ever_rcdom::NodeData;

    if let NodeData::Element {
        ref name,
        ref attrs,
        ..
    } = node.data
    {
        let local = name.local.as_ref();

        if local == "script" {
            collect_script(node, attrs, base, scripts);
        } else if local == "link" {
            collect_modulepreload(attrs, base, scripts);
        }
    }
    for child in node.children.borrow().iter() {
        collect_all(child, base, scripts);
    }
}

/// Classify a `<script>` element based on its attributes.
fn classify_script(script_type: &str, has_src: bool, has_defer: bool, has_async: bool) -> ScriptKind {
    let st = script_type.to_lowercase();

    // importmap — parsed separately, never executed as JS.
    if st.contains("importmap") {
        return ScriptKind::ImportMap;
    }

    // Non-JS types: json, template, html, x-*.
    if st.contains("json") || st.contains("template") || st.contains("html") || st.contains("x-") {
        return ScriptKind::Ignored;
    }

    let is_module = st == "module";

    if is_module {
        if has_async {
            return ScriptKind::AsyncModule;
        }
        if has_src {
            return ScriptKind::Module;
        }
        return ScriptKind::InlineModule;
    }

    // Classic script (empty type, text/javascript, application/javascript, etc.)
    if has_src {
        if has_defer {
            return ScriptKind::Defer;
        }
        if has_async {
            return ScriptKind::Async;
        }
        return ScriptKind::ExternalBlocking;
    }

    // Inline classic — defer/async are ignored on inline scripts per spec.
    ScriptKind::InlineBlocking
}

/// Extract a `<script>` element.
fn collect_script(
    node: &markup5ever_rcdom::Handle,
    attrs: &std::cell::RefCell<Vec<html5ever::Attribute>>,
    base: &str,
    scripts: &mut Vec<ScriptInfo>,
) {
    use markup5ever_rcdom::NodeData;

    let attrs_ref = attrs.borrow();
    let script_type = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "type")
        .map(|a| a.value.to_string())
        .unwrap_or_default();

    let has_defer = attrs_ref
        .iter()
        .any(|a| a.name.local.as_ref() == "defer");
    let has_async = attrs_ref
        .iter()
        .any(|a| a.name.local.as_ref() == "async");
    let src = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "src")
        .map(|a| a.value.to_string());

    let kind = classify_script(&script_type, src.is_some(), has_defer, has_async);

    // Ignored types are dropped entirely.
    if kind == ScriptKind::Ignored {
        return;
    }

    let is_module = matches!(
        kind,
        ScriptKind::Module | ScriptKind::AsyncModule | ScriptKind::InlineModule
    );

    if let Some(src) = src {
        let full = resolve_script_url(&src, base);
        scripts.push(ScriptInfo::External {
            url: full,
            is_module,
            kind,
        });
    } else {
        drop(attrs_ref);
        let text: String = node
            .children
            .borrow()
            .iter()
            .filter_map(|c| match &c.data {
                NodeData::Text { contents } => Some(contents.borrow().to_string()),
                _ => None,
            })
            .collect();
        if !text.trim().is_empty() {
            scripts.push(ScriptInfo::Inline {
                content: text,
                is_module,
                kind,
            });
        }
    }
}

/// Extract `<link rel="modulepreload" href="...">`.
fn collect_modulepreload(
    attrs: &std::cell::RefCell<Vec<html5ever::Attribute>>,
    base: &str,
    scripts: &mut Vec<ScriptInfo>,
) {
    let attrs_ref = attrs.borrow();
    let rel = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "rel")
        .map(|a| a.value.to_string())
        .unwrap_or_default();

    if rel != "modulepreload" {
        return;
    }

    if let Some(href) = attrs_ref
        .iter()
        .find(|a| a.name.local.as_ref() == "href")
        .map(|a| a.value.to_string())
    {
        let full = resolve_script_url(&href, base);
        scripts.push(ScriptInfo::Preload { url: full });
    }
}

/// Detect `<meta http-equiv="refresh" content="...;url=...">` in HTML.
pub(crate) fn detect_meta_refresh(html: &str, base_url: &str) -> Option<String> {
    let lower = html.to_lowercase();
    let needle = "http-equiv";
    let mut search_from = 0;
    while let Some(pos) = lower[search_from..].find(needle) {
        let abs_pos = search_from + pos;
        search_from = abs_pos + needle.len();
        let surrounding = &lower[abs_pos..std::cmp::min(abs_pos + 100, lower.len())];
        if !surrounding.contains("refresh") {
            continue;
        }
        let tag_start = lower[..abs_pos].rfind('<').unwrap_or(abs_pos);
        let tag_end = lower[tag_start..]
            .find('>')
            .map(|p| tag_start + p)
            .unwrap_or(lower.len());
        let tag = &html[tag_start..tag_end];
        let tag_lower = tag.to_lowercase();
        if let Some(ci) = tag_lower.find("content=") {
            let after = &tag[ci + 8..];
            let (delim, start_offset) = if after.starts_with('"') {
                ('"', 1)
            } else if after.starts_with('\'') {
                ('\'', 1)
            } else {
                continue;
            };
            let content_str = &after[start_offset..];
            if let Some(end) = content_str.find(delim) {
                let content_val = &content_str[..end];
                let content_lower = content_val.to_lowercase();
                if let Some(url_pos) = content_lower.find("url=") {
                    let target = content_val[url_pos + 4..].trim();
                    if !target.is_empty() {
                        return Some(resolve_script_url(target, base_url));
                    }
                }
            }
        }
    }
    None
}

/// Resolve a script src URL against a base URL.
pub(crate) fn resolve_script_url(src: &str, base: &str) -> String {
    if src.starts_with("http") {
        src.to_string()
    } else if src.starts_with("//") {
        format!("https:{src}")
    } else if let Ok(base_url) = url::Url::parse(base) {
        base_url
            .join(src)
            .map(|u| u.to_string())
            .unwrap_or_else(|_| src.to_string())
    } else {
        src.to_string()
    }
}

/// Extract the import map from the script list (if any `<script type="importmap">` exists).
///
/// Returns `None` if no import map was found or if the JSON was invalid.
pub(crate) fn extract_import_map(scripts: &[ScriptInfo]) -> Option<ImportMap> {
    for script in scripts {
        if let ScriptInfo::Inline { content, kind, .. } = script {
            if *kind == ScriptKind::ImportMap {
                return ImportMap::parse(content);
            }
        }
    }
    None
}

/// Detect the web framework from HTML signals and script URLs.
///
/// Returns a static string hint for logging/telemetry only.
/// NOT used for any logic or branching.
#[allow(dead_code)]
pub(crate) fn detect_framework(html: &str, script_urls: &[String]) -> &'static str {
    if html.contains("__NEXT_DATA__") || html.contains("_next/static") {
        return "next.js";
    }
    if html.contains("__NUXT__") || html.contains("_nuxt/") {
        return "nuxt";
    }
    if html.contains("__SVELTEKIT") || html.contains("data-svelte-h") {
        return "sveltekit";
    }
    if html.contains("ng-version") {
        return "angular";
    }
    if html.contains("astro-island") {
        return "astro";
    }
    if html.contains("data-reactroot")
        || html.contains("__reactRouterManifest")
        || script_urls.iter().any(|u| u.contains("react"))
    {
        return "react";
    }
    if html.contains("data-v-") || script_urls.iter().any(|u| u.contains("vue")) {
        return "vue";
    }
    "unknown"
}

#[cfg(test)]
mod tests {
    use super::*;

    const BASE: &str = "https://example.com/page";

    /// Helper: extract scripts from HTML and return their kinds.
    fn extract_kinds(html: &str) -> Vec<ScriptKind> {
        extract_scripts(html, BASE)
            .iter()
            .map(|s| s.kind())
            .collect()
    }

    #[test]
    fn test_script_classification_inline_blocking() {
        let html = r#"<html><head><script>var x = 1;</script></head><body></body></html>"#;
        let kinds = extract_kinds(html);
        assert_eq!(kinds, vec![ScriptKind::InlineBlocking]);
    }

    #[test]
    fn test_script_classification_external_blocking() {
        let html = r#"<html><head><script src="/app.js"></script></head><body></body></html>"#;
        let kinds = extract_kinds(html);
        assert_eq!(kinds, vec![ScriptKind::ExternalBlocking]);
    }

    #[test]
    fn test_script_classification_defer() {
        let html = r#"<html><head><script defer src="/app.js"></script></head><body></body></html>"#;
        let kinds = extract_kinds(html);
        assert_eq!(kinds, vec![ScriptKind::Defer]);
    }

    #[test]
    fn test_script_classification_async() {
        let html = r#"<html><head><script async src="/app.js"></script></head><body></body></html>"#;
        let kinds = extract_kinds(html);
        assert_eq!(kinds, vec![ScriptKind::Async]);
    }

    #[test]
    fn test_script_classification_module() {
        let html =
            r#"<html><head><script type="module" src="/app.mjs"></script></head><body></body></html>"#;
        let kinds = extract_kinds(html);
        assert_eq!(kinds, vec![ScriptKind::Module]);
    }

    #[test]
    fn test_script_classification_async_module() {
        let html = r#"<html><head><script type="module" async src="/app.mjs"></script></head><body></body></html>"#;
        let kinds = extract_kinds(html);
        assert_eq!(kinds, vec![ScriptKind::AsyncModule]);
    }

    #[test]
    fn test_script_classification_inline_module() {
        let html =
            r#"<html><head><script type="module">import { x } from "./x.js";</script></head><body></body></html>"#;
        let kinds = extract_kinds(html);
        assert_eq!(kinds, vec![ScriptKind::InlineModule]);
    }

    #[test]
    fn test_importmap_not_executed() {
        let html = r#"<html><head><script type="importmap">{"imports":{}}</script></head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        assert_eq!(scripts.len(), 1);
        assert_eq!(scripts[0].kind(), ScriptKind::ImportMap);
        // ImportMap should be in the list but executor will skip it.
    }

    #[test]
    fn test_ignored_types() {
        let html = r#"<html><head>
            <script type="application/json">{"data": 1}</script>
            <script type="text/template"><div>hi</div></script>
            <script type="text/html"><p>tmpl</p></script>
            <script type="application/x-custom">stuff</script>
        </head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        // All should be classified as Ignored and filtered out by collect_script.
        assert!(scripts.is_empty(), "expected no scripts, got {}", scripts.len());
    }

    #[test]
    fn test_blocking_before_defer_ordering() {
        // Verify that when extract_scripts returns mixed types, they're all present
        // and the executor can partition them correctly.
        let html = r#"<html><head>
            <script defer src="/defer1.js"></script>
            <script>var blocking1 = 1;</script>
            <script type="module" src="/mod1.mjs"></script>
            <script src="/blocking2.js"></script>
            <script async src="/async1.js"></script>
        </head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        let kinds: Vec<ScriptKind> = scripts.iter().map(|s| s.kind()).collect();

        // Document order preserved in the raw list.
        assert_eq!(
            kinds,
            vec![
                ScriptKind::Defer,
                ScriptKind::InlineBlocking,
                ScriptKind::Module,
                ScriptKind::ExternalBlocking,
                ScriptKind::Async,
            ]
        );

        // Verify blocking scripts come before defer in execution groups.
        let blocking: Vec<ScriptKind> = kinds
            .iter()
            .filter(|k| matches!(k, ScriptKind::InlineBlocking | ScriptKind::ExternalBlocking))
            .copied()
            .collect();
        let deferred: Vec<ScriptKind> = kinds
            .iter()
            .filter(|k| matches!(k, ScriptKind::Defer | ScriptKind::Module | ScriptKind::InlineModule))
            .copied()
            .collect();
        assert_eq!(blocking.len(), 2);
        assert_eq!(deferred.len(), 2);
    }

    #[test]
    fn test_module_treated_as_defer() {
        // Module scripts (with src) should be in the deferred group, same as defer.
        let html = r#"<html><head>
            <script type="module" src="/a.mjs"></script>
            <script defer src="/b.js"></script>
        </head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        for s in &scripts {
            assert!(
                matches!(s.kind(), ScriptKind::Module | ScriptKind::Defer),
                "expected Module or Defer, got {:?}",
                s.kind()
            );
        }
    }

    #[test]
    fn test_classify_inline_defer_ignored() {
        // Per HTML spec, defer on inline scripts is meaningless — should still be InlineBlocking.
        let kind = classify_script("", false, true, false);
        assert_eq!(kind, ScriptKind::InlineBlocking);
    }

    #[test]
    fn test_classify_inline_async_ignored() {
        // Per HTML spec, async on inline scripts (non-module) is meaningless.
        let kind = classify_script("", false, false, true);
        assert_eq!(kind, ScriptKind::InlineBlocking);
    }

    #[test]
    fn test_preload_kind_is_module() {
        let html = r#"<html><head>
            <link rel="modulepreload" href="/preloaded.mjs">
        </head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        assert_eq!(scripts.len(), 1);
        assert_eq!(scripts[0].kind(), ScriptKind::Module);
    }

    #[test]
    fn test_is_module_flag_consistency() {
        let html = r#"<html><head>
            <script src="/classic.js"></script>
            <script type="module" src="/mod.mjs"></script>
            <script defer src="/defer.js"></script>
            <script type="module">console.log("inline mod");</script>
        </head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        // classic.js: not module
        assert!(!scripts[0].is_module());
        // mod.mjs: module
        assert!(scripts[1].is_module());
        // defer.js: not module
        assert!(!scripts[2].is_module());
        // inline module: module
        assert!(scripts[3].is_module());
    }

    #[test]
    fn test_extract_import_map_from_scripts() {
        let html = r#"<html><head>
            <script type="importmap">{"imports": {"react": "https://esm.sh/react@18"}}</script>
            <script type="module" src="/app.js"></script>
        </head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        let map = extract_import_map(&scripts).expect("should find import map");
        assert_eq!(map.imports.get("react").unwrap(), "https://esm.sh/react@18");
    }

    #[test]
    fn test_extract_import_map_none_when_missing() {
        let html = r#"<html><head><script src="/app.js"></script></head><body></body></html>"#;
        let scripts = extract_scripts(html, BASE);
        assert!(extract_import_map(&scripts).is_none());
    }

    #[test]
    fn test_framework_detection() {
        assert_eq!(
            detect_framework(r#"<div id="__next"><script id="__NEXT_DATA__">{}</script></div>"#, &[]),
            "next.js"
        );
        assert_eq!(
            detect_framework(r#"<div id="__nuxt"><script>window.__NUXT__={}</script></div>"#, &[]),
            "nuxt"
        );
        assert_eq!(
            detect_framework(r#"<div data-svelte-h="foo">hello</div>"#, &[]),
            "sveltekit"
        );
        assert_eq!(
            detect_framework(r#"<app-root ng-version="17.0.0"></app-root>"#, &[]),
            "angular"
        );
        assert_eq!(
            detect_framework(r#"<astro-island>content</astro-island>"#, &[]),
            "astro"
        );
        assert_eq!(
            detect_framework(r#"<div data-reactroot>app</div>"#, &[]),
            "react"
        );
        assert_eq!(
            detect_framework(r#"<div data-v-abc123>app</div>"#, &[]),
            "vue"
        );
        assert_eq!(
            detect_framework(r#"<html><body>plain</body></html>"#, &[]),
            "unknown"
        );
    }

    #[test]
    fn test_framework_detection_from_urls() {
        assert_eq!(
            detect_framework(
                "<html><body></body></html>",
                &["https://cdn.com/react.production.min.js".to_string()],
            ),
            "react"
        );
        assert_eq!(
            detect_framework(
                "<html><body></body></html>",
                &["https://cdn.com/vue.global.js".to_string()],
            ),
            "vue"
        );
    }
}
