//! `neobrowser tools` — print the catalogue, as JSON or as a Markdown table.
//!
//! The Markdown form is what generates docs/TOOLS.md, so the documentation cannot drift
//! from the binary: it is produced by the binary.

use neobrowser::tool_impls;

/// Print the tool catalog. `tools --markdown` renders a docs-friendly table.
pub fn print_tools() {
    let registry = tool_impls::build_registry();
    let descriptors = registry.descriptors();
    let markdown = std::env::args().any(|a| a == "--markdown" || a == "md");
    if !markdown {
        println!(
            "{}",
            serde_json::to_string_pretty(&descriptors).unwrap_or_else(|_| "[]".into())
        );
        return;
    }
    println!("# NeoBrowser tools ({})\n", descriptors.len());
    println!("Generated by `neobrowser tools --markdown`.\n");
    for d in &descriptors {
        let name = d.get("name").and_then(|v| v.as_str()).unwrap_or("");
        let desc = d.get("description").and_then(|v| v.as_str()).unwrap_or("");
        println!("## `{name}`\n\n{desc}\n");
        let props = d
            .get("inputSchema")
            .and_then(|s| s.get("properties"))
            .and_then(|p| p.as_object());
        let required: Vec<&str> = d
            .get("inputSchema")
            .and_then(|s| s.get("required"))
            .and_then(|r| r.as_array())
            .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        match props {
            Some(p) if !p.is_empty() => {
                println!("| param | type | required | description |");
                println!("|---|---|---|---|");
                for (k, v) in p {
                    let ty = v.get("type").and_then(|t| t.as_str()).unwrap_or("");
                    let pd = v.get("description").and_then(|t| t.as_str()).unwrap_or("");
                    let req = if required.contains(&k.as_str()) {
                        "yes"
                    } else {
                        ""
                    };
                    println!("| `{k}` | {ty} | {req} | {pd} |");
                }
                println!();
            }
            _ => println!("_No parameters._\n"),
        }
    }
}
